<a href="https://colab.research.google.com/github/pushpagupta198612-eng/ML-EXPS/blob/main/ML%20EXP%205%2027.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NAME - GAURAV R GUPTA**
**ROLL N0.- 27**
**BATCH - 2**
**TITLE - Disease Prediction using Naive Bayes and Neural Network with Comparison of Classifiers**

In [ ]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score , precision_score,recall_score ,f1_score,roc_auc_score,confusion_matrix, classification_report

In [ ]:
data = load_breast_cancer()
x=data.data
y=data.target

print("Classes:",data.target_names)

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.3)

Classes: ['malignant' 'benign']

In [ ]:
print(data.data.shape)

(569, 30)

In [ ]:
import pandas as pd
df = pd.DataFrame(data.data)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       569 non-null    float64
 1   1       569 non-null    float64
 2   2       569 non-null    float64
 3   3       569 non-null    float64
 4   4       569 non-null    float64
 5   5       569 non-null    float64
 6   6       569 non-null    float64
 7   7       569 non-null    float64
 8   8       569 non-null    float64
 9   9       569 non-null    float64
 10  10      569 non-null    float64
 11  11      569 non-null    float64
 12  12      569 non-null    float64
 13  13      569 non-null    float64
 14  14      569 non-null    float64
 15  15      569 non-null    float64
 16  16      569 non-null    float64
 17  17      569 non-null    float64
 18  18      569 non-null    float64
 19  19      569 non-null    float64
 20  20      569 non-null    float64
 21  21      569 non-null    float64
 22  22      569 non-null    float64
 23  23      569 non-null    float64
 24  24      569 non-null    float64
 25  25      569 non-null    float64
 26  26      569 non-null    float64
 27  27      569 non-null    float64
 28  28      569 non-null    float64
 29  29      569 non-null    float64
dtypes: float64(30)
memory usage: 133.5 KB

In [ ]:
df.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
dtype: int64

**LOGISTIC REGRESSION**

In [22]:
lr = LogisticRegression(max_iter=5000)
lr.fit(x_train,y_train)
pred_lr = lr.predict(x_test)
print("Logistic TestAcurracy:",accuracy_score(y_test,pred_lr))
pred_lr_train = lr.predict(x_train)
print("Logistic TrainAccuracy:",accuracy_score(y_train,pred_lr_train))

Logistic TestAcurracy: 0.9590643274853801
Logistic TrainAccuracy: 0.9623115577889447

**DECISION TREE**

In [23]:
dt = DecisionTreeClassifier()
dt.fit(x_train,y_train)
pred_dt = dt.predict(x_test)
print("Decision Tree TestAcurracy:",accuracy_score(y_test,pred_dt))
pred_dt_train = dt.predict(x_train)
print("Decicsion TrainAccuracy:",accuracy_score(y_train,pred_dt_train))

Decision Tree TestAcurracy: 0.9298245614035088
Decicsion TrainAccuracy: 1.0

**KNN**

In [24]:
knn = KNeighborsClassifier()
knn.fit(x_train,y_train)
pred_knn = knn.predict(x_test)
print("KNN Tree TestAcurracy:",accuracy_score(y_test,pred_knn))
pred_knn_train = knn.predict(x_train)
print("TrainAccuracy:",accuracy_score(y_train,pred_knn_train))

KNN Tree TestAcurracy: 0.9415204678362573
TrainAccuracy: 0.9472361809045227

**NAIVE BAYES**

In [25]:
nb = GaussianNB()
nb.fit(x_train,y_train)
pred_nb = nb.predict(x_test)
print("  GaussianN Naive Bayes Tree TestAcurracy:",accuracy_score(y_test,pred_nb))
pred_nb_train = nb.predict(x_train)
print(" GaussianN Naive Bayes TrainAccuracy:",accuracy_score(y_train,pred_nb_train))

  GaussianN Naive Bayes Tree TestAcurracy: 0.9298245614035088
 GaussianN Naive Bayes TrainAccuracy: 0.9447236180904522

**NEURAL NETWORK**

In [26]:
nn = MLPClassifier ()
nn.fit(x_train,y_train)
pred_nn = nn.predict(x_test)
print("Neural Network Tree TestAcurracy:",accuracy_score(y_test,pred_nn))
pred_nn_train = nn.predict(x_train)
print("Neural Network TrainAccuracy:",accuracy_score(y_train,pred_nn_train))

Neural Network Tree TestAcurracy: 0.9415204678362573
Neural Network TrainAccuracy: 0.9422110552763819

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

In [27]:
precision_lr = precision_score(y_test,pred_lr)

In [29]:
precision_lr = precision_score(y_test,pred_lr)
recall_lr = recall_score(y_test,pred_lr)
f1 = f1_score(y_test,pred_lr)
roc_auc = roc_auc_score(y_test,pred_lr)

In [30]:
precision_dt = precision_score(y_test,pred_dt)
recall_lr = recall_score(y_test,pred_dt)
f1 = f1_score(y_test,pred_dt)
roc_auc = roc_auc_score(y_test,pred_dt)

**PART B**
**LR CONFUSION MATRIX**

In [37]:
cm_lr = confusion_matrix (y_test , pred_lr)
print("\nLogistic Regression Confusion Matrix :")
print(cm_lr)
TN1 , FP1 ,FN1 , TP1 = cm_lr.ravel()
type1_lr = FP1 / (FP1 + TN1)
type2_lr = FN1 / (FN1 + TP1)

print("FP1 (Type-1):",FP1)
print("FN1 (Type-2:)",FN1)
print("Type-1 Error Rate in %:",type1_lr*100)
print("Type-2 Error Rate in %:",type2_lr*100)

precision = precision_score(y_test,pred_lr)
recall = recall_score(y_test , pred_lr)
f1 = f1_score(y_test , pred_lr)
roc = roc_auc_score(y_test , pred_lr)


print("Precision:",precision)
print("Recall:",recall)
print("f1:",f1)
print("Roc:",roc)

Logistic Regression Confusion Matrix :
[[ 56   7]
 [  0 108]]
FP1 (Type-1): 7
FN1 (Type-2:) 0
Type-1 Error Rate in %: 11.11111111111111
Type-2 Error Rate in %: 0.0
Precision: 0.9391304347826087
Recall: 1.0
f1: 0.968609865470852
Roc: 0.9444444444444444

**DECISION TREE**

In [38]:
cm_dt = confusion_matrix (y_test , pred_dt)
print("\nDecision Tree Confusion Matrix :")
print(cm_dt)
TN2 , FP2 ,FN2 , TP2 = cm_dt.ravel()
type1_dt = FP2 / (FP2 + TN2)
type2_dt = FN2 / (FN2 + TP2)

print("FP2 (Type-1):",FP2)
print("FN (Type-2:)",FN2)
print("Type-1 Error Rate in %:",type1_dt*100)
print("Type-2 Error Rate in %:",type2_dt*100)

precision = precision_score(y_test,pred_dt)
recall = recall_score(y_test , pred_dt)
f1 = f1_score(y_test , pred_dt)
roc = roc_auc_score(y_test , pred_dt)

print("Precision:",precision)
print("Recall:",recall)
print("f1:",f1)
print("Roc:",roc)

Decision Tree Confusion Matrix :
[[ 54   9]
 [  3 105]]
FP2 (Type-1): 9
FN (Type-2:) 3
Type-1 Error Rate in %: 14.285714285714285
Type-2 Error Rate in %: 2.7777777777777777
Precision: 0.9210526315789473
Recall: 0.9722222222222222
f1: 0.9459459459459459
Roc: 0.9146825396825398

**KNN**

In [39]:
cm_knn = confusion_matrix (y_test , pred_knn)
print("\nKNN Confusion Matrix :")
print(cm_knn)
TN3 , FP3 ,FN3 , TP3 = cm_knn.ravel()
type1_knn = FP3 / (FP3 + TN3)
type2_knn = FN3 / (FN3 + TP3)

print("FP3 (Type-1):",FP3)
print("FN3 (Type-2:)",FN3)
print("Type-1 Error Rate in %:",type1_knn*100)
print("Type-2 Error Rate in %:",type2_knn*100)

precision = precision_score(y_test,pred_knn)
recall = recall_score(y_test , pred_knn)
f1 = f1_score(y_test , pred_knn)
roc = roc_auc_score(y_test , pred_knn)

print("Precision:",precision)
print("Recall:",recall)
print("f1:",f1)
print("Roc:",roc)

KNN Confusion Matrix :
[[ 56   7]
 [  3 105]]
FP3 (Type-1): 7
FN3 (Type-2:) 3
Type-1 Error Rate in %: 11.11111111111111
Type-2 Error Rate in %: 2.7777777777777777
Precision: 0.9375
Recall: 0.9722222222222222
f1: 0.9545454545454546
Roc: 0.9305555555555556

**NAIVE BAYES**

In [40]:
cm_nb = confusion_matrix (y_test , pred_nb)
print("\nNavie Bayes Confusion Matrix :")
print(cm_nb)
TN4 , FP4 ,FN4 , TP4 = cm_nb.ravel()
type1_nb = FP4 / (FP4 + TN4)
type2_nb = FN4 / (FN4 + TP4)

print("FP4 (Type-1):",FP4)
print("FN4 (Type-2:)",FN4)
print("Type-1 Error Rate in %:",type1_nb*100)
print("Type-2 Error Rate in %:",type2_nb*100)

precision = precision_score(y_test,pred_nb)
recall = recall_score(y_test , pred_nb)
f1 = f1_score(y_test , pred_nb)
roc = roc_auc_score(y_test , pred_nb)

print("Precision:",precision)
print("Recall:",recall)
print("f1:",f1)
print("Roc:",roc)

Navie Bayes Confusion Matrix :
[[ 54   9]
 [  3 105]]
FP4 (Type-1): 9
FN4 (Type-2:) 3
Type-1 Error Rate in %: 14.285714285714285
Type-2 Error Rate in %: 2.7777777777777777
Precision: 0.9210526315789473
Recall: 0.9722222222222222
f1: 0.9459459459459459
Roc: 0.9146825396825398

**NEURAL NETWORK**

In [41]:
cm_nn = confusion_matrix (y_test , pred_nn)
print("\nNavie Bayes Confusion Matrix :")
print(cm_nn)
TN5 , FP5 ,FN5 , TP5 = cm_nn.ravel()
type1_nn = FP5 / (FP5 + TN5)
type2_nn = FN5 / (FN5 + TP5)

print("FP5 (Type-1):",FP5)
print("FN5 (Type-2:)",FN5)
print("Type-1 Error Rate in %:",type1_nn*100)
print("Type-2 Error Rate in %:",type2_nn*100)

precision = precision_score(y_test,pred_nn)
recall = recall_score(y_test , pred_nn)
f1 = f1_score(y_test , pred_nn)
roc = roc_auc_score(y_test , pred_nn)

print("Precision:",precision)
print("Recall:",recall)
print("f1:",f1)
print("Roc:",roc)

Navie Bayes Confusion Matrix :
[[ 54   9]
 [  1 107]]
FP5 (Type-1): 9
FN5 (Type-2:) 1
Type-1 Error Rate in %: 14.285714285714285
Type-2 Error Rate in %: 0.9259259259259258
Precision: 0.9224137931034483
Recall: 0.9907407407407407
f1: 0.9553571428571429
Roc: 0.9239417989417991